version: '3.8'

services:
  auth_db:
    image: postgres:13
    container_name: auth_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - core_network

  redis:
    image: redis:7
    container_name: auth_redis
    networks:
      - core_network

  auth:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth_app
    volumes:
      - ./src:/app/src
      - ./alembic:/app/alembic
    ports:
      - "8001:8000"
    depends_on:
      - auth_db
      - redis
    env_file:
      - .env
    networks:
      - core_network

networks:
  core_network:
    external: true

volumes:
  auth_postgres_data:
