"""Add cascade delete

Revision ID: 0c3a581e375c
Revises: 22c403869e58
Create Date: 2025-02-23 14:21:32.433468

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0c3a581e375c"
down_revision: Union[str, None] = "22c403869e58"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "role_permissions_permission_id_fkey", "role_permissions", type_="foreignkey"
    )
    op.drop_constraint("role_permissions_role_id_fkey", "role_permissions", type_="foreignkey")
    op.create_foreign_key(None, "role_permissions", "role", ["role_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(
        None,
        "role_permissions",
        "permission",
        ["permission_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "user_permissions_permission_id_fkey", "user_permissions", type_="foreignkey"
    )
    op.drop_constraint("user_permissions_user_id_fkey", "user_permissions", type_="foreignkey")
    op.create_foreign_key(None, "user_permissions", "user", ["user_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(
        None,
        "user_permissions",
        "permission",
        ["permission_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_permissions", type_="foreignkey")
    op.drop_constraint(None, "user_permissions", type_="foreignkey")
    op.create_foreign_key(
        "user_permissions_user_id_fkey", "user_permissions", "user", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        "user_permissions_permission_id_fkey",
        "user_permissions",
        "permission",
        ["permission_id"],
        ["id"],
    )
    op.drop_constraint(None, "role_permissions", type_="foreignkey")
    op.drop_constraint(None, "role_permissions", type_="foreignkey")
    op.create_foreign_key(
        "role_permissions_role_id_fkey", "role_permissions", "role", ["role_id"], ["id"]
    )
    op.create_foreign_key(
        "role_permissions_permission_id_fkey",
        "role_permissions",
        "permission",
        ["permission_id"],
        ["id"],
    )
    # ### end Alembic commands ###
