"""Add avatar field in User model

Revision ID: 22c403869e58
Revises: 95ba743720cc
Create Date: 2025-02-14 19:50:14.473923

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "22c403869e58"
down_revision: Union[str, None] = "95ba743720cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("avatar", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "avatar")
    # ### end Alembic commands ###
